### PR TITLE
Revert "mem-ruby: add StashOnce*PoC and StashOnce* flow"

### PR DESCRIPTION
**Pull request by erin-le**
PR https://github.com/gem5/gem5/pull/2975 is causing the `gem5/memory` tests in the Daily Tests to fail. The specific test that failed was `ruby_mem_test-simple-extra-multicore-NULL-x86_64-opt`, which can be run with the following command:

```
build/NULL/gem5.opt configs/example/ruby_mem_test.py --abs-max-tick 20000000 --functional 10 --network=simple --simple-physical-channels --num-cpus=4
```

The error message is as follows:

```
AttributeError: object 'MemTest' has no attribute 'l2'

At:
  src/python/m5/SimObject.py(873): __getattr__
  /__w/gem5/gem5/configs/example/ruby_mem_test.py(210): <module>
  src/python/m5/main.py(687): main
```

This error can be fixed by replacing lines 208-211 in `configs/example/ruby_mem_test.py` with the following code snippet:

```python
# Set the stash node IDs for each CPU after C++ objects are constructed.
if buildEnv["PROTOCOL"] == "CHI":
    for cpu in cpus:
        cpu.set_stash_node_ids([_.l2.version for _ in cpus if _ != cpu])
        cpu.set_stash_lp_ids([_.l1d.version for _ in cpus if _ != cpu])
```

However, once this error is fixed, another failure arises:

```
system.cpu3: completed 23000 read, 12621 write, 0 atomic accesses, 0 stash once accesses @7613928
system.cpu2: completed 23000 read, 12632 write, 0 atomic accesses, 0 stash once accesses @7617227
system.cpu0: completed 23000 read, 12524 write, 0 atomic accesses, 0 stash once accesses @7623170
src/cpu/testers/memtest/memtest.cc:158: panic: Read access failed at 0x40af81
Memory Usage: 740132 KBytes
Panic at tick 7662183
Program aborted at tick 7662183
--- BEGIN LIBC BACKTRACE ---
```

`git bisect` identifies both of these errors as being caused by commit a179af30568d17ad3ad88a3e996292784c605b1b, which is the second commit in the PR.

### CODE REVIEW

**Comment by erin-le** [comment]
@tsyw: Just a heads up about this. Could you take a look if you get a chance? Thank you!

**Review by powerjg — APPROVED** [review]

**Comment by powerjg** [comment]
Let's merge the revert to get tests passing again. Hopefully, we'll have a permanent fix soon.

**Comment by tsyw** [comment]
> @tsyw: Just a heads up about this. Could you take a look if you get a chance? Thank you!

@erin-le @giactra  

I have isolated the second failure independently.

Using develop branch, the command runs successfully. I then added only one line in memtest.cc and the panic is reproduced with the same panic ticks and address:

```bash
diff --git a/src/cpu/testers/memtest/memtest.cc b/src/cpu/testers/memtest/memtest.cc
index f1650af1f4..e6b584c0f1 100644
--- a/src/cpu/testers/memtest/memtest.cc
+++ b/src/cpu/testers/memtest/memtest.cc
@@ -245,6 +245,7 @@ MemTest::tick()
     bool uncacheable = rng->random(0, 100) < percentUncacheable;
     bool do_atomic = (rng->random(0, 100) < percentAtomic) &&
                      !uncacheable;
+    (void)rng->random(0, 100);
     unsigned base = rng->random(0, 1);
     Request::Flags flags;
     Addr paddr;
```
Here is the protocol trace:

```text
7661628  L1Cache-1  Data             IM>M   0x40af80
7661628  L1Cache-1  Replacement      M>MI   0x40af80
7662143  Directory  GETX             M>M    owner=L1Cache-1 requester=L1Cache-3
7662147  Directory  PUTX_NotOwner    M>M    0x40af80
7662183  functional read 0x40af81: num_maybe_stale=1, num_busy=1
7662183  read completes with an error
```

Do you have any information about this situation?
