### PR TITLE
base, dev: Replace libdnet with POSIX standard netinet header

### PR DESCRIPTION
**Pull request by rogerchang23424**
Replace libdnet with POSIX standard netinet header to avoid ODR violation

```
ext/dnet/ip6.h:36: warning: type ‘union <anon>’ violates the C++ One Definition Rule [-Wodr]
   36 |         union {
/usr/include/netinet/ip6.h:27: note: a different type is defined in another translation unit
   27 |       {
ext/dnet/ip6.h:42: note: the first difference of corresponding definitions is field ‘ip6_un1’
   42 |                 } ip6_un1;
/usr/include/netinet/ip6.h:35: note: a field of same name but different type is defined in another translation unit
   35 |           } ip6_un1;
ext/dnet/ip6.h:37: note: type name ‘ip6_hdr::{unnamed type#1}::ip6_hdr_ctl’ should match type name ‘ip6_hdr::{unnamed type#1}::ip6_hdrctl’
   37 |                 struct ip6_hdr_ctl {
/usr/include/netinet/ip6.h:28: note: the incompatible type is defined here
   28 |         struct ip6_hdrctl
```

### CODE REVIEW

**Review by powerjg — APPROVED** [review]

**Comment by abmerop** [comment]
This PR is causing our builds to fail on batch machines after merging (RHEL 8, multiple gcc versions 13+, multiple glibc 2.28, 2.39). I and an agent have spent a few hours trying to figure out why with no success. I wanted to see if you might have any idea what the issue is @rogerchang23424 ?

```
src/base/inet.hh: In member function ‘uint16_t gem5::networking::TcpHdr::sport() const’:                                                                                                                                                                                                                                    src/base/inet.hh:822:43: error: ‘th_sport’ was not declared in this scope; did you mean ‘sport’?
  822 |     uint16_t sport() const { return ntohs(th_sport); }
      |                                           ^~~~~~~~
src/base/inet.hh: In member function ‘uint16_t gem5::networking::TcpHdr::dport() const’:                                                                                                                                                                                                                                    src/base/inet.hh:823:43: error: ‘th_dport’ was not declared in this scope; did you mean ‘dport’?                                                                                                                                                                                                                              823 |     uint16_t dport() const { return ntohs(th_dport); }
      |                                           ^~~~~~~~                                                                                                                                                                                                                                                                  src/base/inet.hh: In member function ‘uint32_t gem5::networking::TcpHdr::seq() const’:                                                                                                                                                                                                                                      src/base/inet.hh:824:41: error: ‘th_seq’ was not declared in this scope
  824 |     uint32_t seq() const { return ntohl(th_seq); }                                                                                                                                                                                                                                                                        |                                         ^~~~~~                                                                                                                                                                                                                                                                      src/base/inet.hh: In member function ‘uint32_t gem5::networking::TcpHdr::ack() const’:
src/base/inet.hh:825:41: error: ‘th_ack’ was not declared in this scope; did you mean ‘hack’?
  825 |     uint32_t ack() const { return ntohl(th_ack); }                                                                                                                                                                                                                                                                        |                                         ^~~~~~
src/base/inet.hh: In member function ‘uint8_t gem5::networking::TcpHdr::off() const’:
src/base/inet.hh:826:35: error: ‘th_off’ was not declared in this scope                                                                                                                                                                                                                                                       826 |     uint8_t  off() const { return th_off*4; }                                                                                                                                                                                                                                                                             |                                   ^~~~~~
src/base/inet.hh: In member function ‘uint8_t gem5::networking::TcpHdr::flags() const’:
src/base/inet.hh:827:37: error: ‘th_flags’ was not declared in this scope; did you mean ‘flags’?                                                                                                                                                                                                                              827 |     uint8_t  flags() const { return th_flags & 0x3f; }                                                                                                                                                                                                                                                                    |                                     ^~~~~~~~
      |                                     flags
src/base/inet.hh: In member function ‘uint16_t gem5::networking::TcpHdr::win() const’:                                                                                                                                                                                                                                      src/base/inet.hh:828:41: error: ‘th_win’ was not declared in this scope                                                                                                                                                                                                                                                       828 |     uint16_t win() const { return ntohs(th_win); }
      |                                         ^~~~~~
src/base/inet.hh: In member function ‘uint16_t gem5::networking::TcpHdr::sum() const’:                                                                                                                                                                                                                                      src/base/inet.hh:829:35: error: ‘th_sum’ was not declared in this scope                                                                                                                                                                                                                                                       829 |     uint16_t sum() const { return th_sum; }
      |                                   ^~~~~~
```

It seems like some #define is missing on this environment. I've tried setting __USE_MISC, __FAVOR_BSD, _GNU_SOURCE, etc. to no avail.

**Comment by giactra** [comment]
> This PR is causing our builds to fail on batch machines after merging (RHEL 8, multiple gcc versions 13+, multiple glibc 2.28, 2.39). I and an agent have spent a few hours trying to figure out why with no success. I wanted to see if you might have any idea what the issue is @rogerchang23424 ?
> 
> ```
> src/base/inet.hh: In member function ‘uint16_t gem5::networking::TcpHdr::sport() const’:                                                                                                                                                                                                                                    src/base/inet.hh:822:43: error: ‘th_sport’ was not declared in this scope; did you mean ‘sport’?
>   822 |     uint16_t sport() const { return ntohs(th_sport); }
>       |                                           ^~~~~~~~
> src/base/inet.hh: In member function ‘uint16_t gem5::networking::TcpHdr::dport() const’:                                                                                                                                                                                                                                    src/base/inet.hh:823:43: error: ‘th_dport’ was not declared in this scope; did you mean ‘dport’?                                                                                                                                                                                                                              823 |     uint16_t dport() const { return ntohs(th_dport); }
>       |                                           ^~~~~~~~                                                                                                                                                                                                                                                                  src/base/inet.hh: In member function ‘uint32_t gem5::networking::TcpHdr::seq() const’:                                                                                                                                                                                                                                      src/base/inet.hh:824:41: error: ‘th_seq’ was not declared in this scope
>   824 |     uint32_t seq() const { return ntohl(th_seq); }                                                                                                                                                                                                                                                                        |                                         ^~~~~~                                                                                                                                                                                                                                                                      src/base/inet.hh: In member function ‘uint32_t gem5::networking::TcpHdr::ack() const’:
> src/base/inet.hh:825:41: error: ‘th_ack’ was not declared in this scope; did you mean ‘hack’?
>   825 |     uint32_t ack() const { return ntohl(th_ack); }                                                                                                                                                                                                                                                                        |                                         ^~~~~~
> src/base/inet.hh: In member function ‘uint8_t gem5::networking::TcpHdr::off() const’:
> src/base/inet.hh:826:35: error: ‘th_off’ was not declared in this scope                                                                                                                                                                                                                                                       826 |     uint8_t  off() const { return th_off*4; }                                                                                                                                                                                                                                                                             |                                   ^~~~~~
> src/base/inet.hh: In member function ‘uint8_t gem5::networking::TcpHdr::flags() const’:
> src/base/inet.hh:827:37: error: ‘th_flags’ was not declared in this scope; did you mean ‘flags’?                                                                                                                                                                                                                              827 |     uint8_t  flags() const { return th_flags & 0x3f; }                                                                                                                                                                                                                                                                    |                                     ^~~~~~~~
>       |                                     flags
> src/base/inet.hh: In member function ‘uint16_t gem5::networking::TcpHdr::win() const’:                                                                                                                                                                                                                                      src/base/inet.hh:828:41: error: ‘th_win’ was not declared in this scope                                                                                                                                                                                                                                                       828 |     uint16_t win() const { return ntohs(th_win); }
>       |                                         ^~~~~~
> src/base/inet.hh: In member function ‘uint16_t gem5::networking::TcpHdr::sum() const’:                                                                                                                                                                                                                                      src/base/inet.hh:829:35: error: ‘th_sum’ was not declared in this scope                                                                                                                                                                                                                                                       829 |     uint16_t sum() const { return th_sum; }
>       |                                   ^~~~~~
> ```
> 
> It seems like some #define is missing on this environment. I've tried setting __USE_MISC, __FAVOR_BSD, _GNU_SOURCE, etc. to no avail.

I was about to post the same... We have the same issue (RHE8). I suspect that if we want to move to POSIX we need to address portability issues within the build system to generate the proper flags

@abmerop have you tried _DEFAULT_SOURCE?

**Comment by abmerop** [comment]
> @abmerop have you tried _DEFAULT_SOURCE?

Just tried it. This also fails to build.

**Comment by giactra** [comment]
Ok, so I managed to build in my RHE machine by defining FAVOR_BSD just before including tcp.h:

```
#define __FAVOR_BSD 1
#include <netinet/tcp.h>
```

Note: it was not working when using CFLAGS

**Comment by abmerop** [comment]
> Ok, so I managed to build in my RHE machine by defining FAVOR_BSD just before including tcp.h:
> 
> ```
> #define __FAVOR_BSD 1
> #include <netinet/tcp.h>
> ```
> 
> Note: it was not working when using CFLAGS

Thanks, that worked for me too. I was using CFLAGS previously and that did not work.

**Comment by rogerchang23424** [comment]
Hi @abmerop and @giactra,

     Sorry I'm not familiar with RHEL, I can't provide the suggestion. If the following suggestion works on RHEL, do we need to create PR to fix it?

> Ok, so I managed to build in my RHE machine by defining FAVOR_BSD just before including tcp.h:
> 
> ```
> #define __FAVOR_BSD 1
> #include <netinet/tcp.h>
> ```
> 
> Note: it was not working when using CFLAGS
