### ISSUE TITLE
gcc 12.3.0 appears to fail to build

### ISSUE THREAD

**Issue by Mattwmaster58** [gem5/gem5#280]
**Describe the bug**
Trying to compile with GCC 12.3.0, I get this error:
```
...
scons: done reading SConscript files.
scons: Building targets ...
 [VER TAGS]  -> ARM/sim/tags.cc
 [    LINK]  -> ARM/gem5.opt
/usr/bin/ld: build/ARM/cpu/o3/probe/elastic_trace.o: undefined reference to symbol '_ZN4absl12lts_2023012512log_internal17MakeCheckOpStringIllEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_T0_PKc'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib/libabsl_log_internal_check_op.so.2301.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Affects version**
[48a40cf](https://github.com/gem5/gem5/commit/48a40cf2f5182a82de360b7efa497d82e06b1631) (stable)

**gem5 Modifications**
N/A

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:
1. git clone
2. `scons build/ARM/gem5.opt`

**Expected behavior**
Compiles successfully

**Host Operating System**
Ubuntu 22.04, Mac OS X, etc.

**Host ISA**
x86-64

**Compiler used**
GCC 12.3.0

**Additional information**
I have found a workaround for now and wanted other to be aware.
I googled the some keywords from the error and (found this comment)[https://aur.archlinux.org/pkgbase/eternalterminal#comment-923180]. Since I was unfamiliar with scons, I symlinked /usr/bin/g++-12 and /usr/bin/gcc-12 to /usr/bin/12/*, then set my PATH to /usr/bin/12:$PATH. Then I read the Sconsstruct file and based on the commands from the AUR comment, I set LINKER_EXTRA="-Wl,--copy-dt-needed-entries". So my full workaround command:
```
PATH=/usr/bin/12:$PATH;CCFLAGS_EXTRA='-DDISABLE_VCPKG=ON -DCMAKE_CXX_COMPILER=/usr/bin/gcc-12 -DCMAKE_EXE_LINKER_FLAGS="-Wl,--copy-dt-needed-entries" -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--copy-dt-needed-entries"' scons -j24 build/ARM/gem5.opt
```

I am unsure if this is the fault of this code or my system

**Comment by mkjost0** [comment]
Hi, I've tried reproducing this locally, and I've been able to have gem5 compile successfully when using GCC 12.3.0, so I believe this was probably an issue with the system.
