### PR TITLE
misc: Fixup optional libs being required

### PR DESCRIPTION
**Pull request by odanrc**
hdf5, protobuf, libpng and kvm should not be required in the gem5 lib. Fix this by checking in the scons files if they are present before declaring the source files that use them.

### CODE REVIEW

**Review by abmerop — DISMISSED** [review]
Working for me I believe (I had installed libhdf5-dev as temporarily but still works after removing)

**Review by powerjg — DISMISSED** [review]

**Comment by rogerchang23424** [comment]
I think it just fixed the issue of hdf5 dependency, the other dependency issues still exist

Got compile error at the top of PR within `ghcr.io/gem5/ubuntu-24.04_min-dependencies:v24-1`

```
scons: *** [build/ALL/proto/packet.pb.cc] Error 127
scons: building terminated because of errors.
```

We should ensure the gem5 can be compiled with min dependencies

**Review by BobbyRBruce — DISMISSED** [review]

**Review by abmerop — DISMISSED** [review]

**Comment by rogerchang23424** [comment]
Got error while building `libgem5_opt.so`

Compile Command:
```bash
scons defconfig build/ARM build_opts/ARM
scons setconfig build/ARM USE_SYSTEMC=n
scons --with-cxx-config --without-python --without-tcmalloc -j24 build/ARM/libgem5_opt.so
```

Output:
```bash
TypeError: SourceFilter.__init__() missing 1 required positional argument: 'predicate':
  File "/gem5/SConstruct", line 971:
    SConscript('src/SConscript', variant_dir=variant_path, exports=exports,
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 662:
    return method(*args, **kw)
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/gem5/src/SConscript", line 723:
    lib_filter = lib_filter & without_tag('python')
  File "/gem5/site_scons/gem5_scons/sources.py", line 143:
    return SourceFilter(
```

**Comment by odanrc** [comment]
> Got error while building `libgem5_opt.so`
> 
> Compile Command:
> 
> ```shell
> scons defconfig build/ARM build_opts/ARM
> scons setconfig build/ARM USE_SYSTEMC=n
> scons --with-cxx-config --without-python --without-tcmalloc -j24 build/ARM/libgem5_opt.so
> ```
> 
> Output:
> 
> ```shell
> TypeError: SourceFilter.__init__() missing 1 required positional argument: 'predicate':
>   File "/gem5/SConstruct", line 971:
>     SConscript('src/SConscript', variant_dir=variant_path, exports=exports,
>   File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 662:
>     return method(*args, **kw)
>   File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 598:
>     return _SConscript(self.fs, *files, **subst_kw)
>   File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 285:
>     exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
>   File "/gem5/src/SConscript", line 723:
>     lib_filter = lib_filter & without_tag('python')
>   File "/gem5/site_scons/gem5_scons/sources.py", line 143:
>     return SourceFilter(
> ```

Here is a fix for this issue: https://github.com/gem5/gem5/pull/1918

**Comment by giactra** [comment]
I have to say I don't really understand at this point what's the purpose of tagging, other than a convenient way for listing dependent files (e.g. for GTest)

I thought using tags would make the use of

`if env['CONF']['HAVE_HDF5']:`

unnecessary. That is how SConscripts were before the introduction of tags IIRC.

While I appreciate how responsive you are to the incoming issues, I am also concerned about the PR swinging so quickly from one solution to the other... What makes you prefer this solution wrt the previous one? How are we supposed to tag optional libs?

**Comment by powerjg** [comment]
I again say that the scons build system, the kconfig static configuration system, and things like these "tags" are far too complicated. I think we have ended up *way* over engineering this. That said, we need to dig ourselves out of this hole in the short term and make sure that all of our targets build correctly. 

Just throwing this idea out there (I'm not advocating for this), but we could revert #1785 and take a fresh approach if we can't easily "patch" over the fixes.

@odanrc does this comment https://github.com/gem5/gem5/pull/1785#issuecomment-2533171895 still have accurate documentation on how to use the tags, or have these changes modified the API?

**Comment by odanrc** [comment]
> I have to say I don't really understand at this point what's the purpose of tagging, other than a convenient way for listing dependent files (e.g. for GTest)
> 
> I thought using tags would make the use of
> 
> `if env['CONF']['HAVE_HDF5']:`
> 
> unnecessary. That is how SConscripts were before the introduction of tags IIRC.
> 

This seems to be the commit that adds the tags: https://gem5-review.googlesource.com/c/public/gem5/+/5822

It does not seem to specify that they were supposed to replace the use of those env checks. For reference, since I have started adding unit tests I have been using them to group files to make declaring the test dependencies easier/less error prone. I thought that was what they were for.

While I agree that they could be used to hide away portions of the code that use optional libs, that does not seem right. For example, the cpu traces use protobuf. IMHO, the cpu traces are part of the gem5 lib... but they require protobuf, so the protobuf tag needs to be included if the cpu trace is compiled, which makes protobuf no longer optional. So in order to be able to tag the cpu traces with gem5 lib, the files must be conditionally compiled, which requires the env check. BTW, in the SConsopts file protobuf implies gem5 lib anyway.

I think these opt libs were working before out of coincidence, because the bug I fixed was creating a lot of inexistent dependencies.

> While I appreciate how responsive you are to the incoming issues, I am also concerned about the PR swinging so quickly from one solution to the other... What makes you prefer this solution wrt the previous one?

I tried the tag_gem5_lib=False approach to solve the protobuf situation, got stuck and backtracked to using the env checks. Then I realized what I mentioned in the 2 previous paragraphs, and made up my mind that it was indeed better to use env checks.

>  How are we supposed to tag optional libs?

Normally, with the name of the optional lib, but its Source() declarations should be within a conditional env check scope. See any of the files tagged with one of the optional libs, in this PR.

**Comment by odanrc** [comment]
> I again say that the scons build system, the kconfig static configuration system, and things like these "tags" are far too complicated. I think we have ended up _way_ over engineering this. That said, we need to dig ourselves out of this hole in the short term and make sure that all of our targets build correctly.

Agreed. I didn´t want to have to touch scons at all, but there was a bug that was blocking SimObject unit tests from happening. It was a mess to understand and debug those files.

> 
> Just throwing this idea out there (I'm not advocating for this), but we could revert #1785 and take a fresh approach if we can't easily "patch" over the fixes.

I think the fixes are trivial now that I know where to look (although I do not necessarily know how it works ;) ), and things should be good after these 2 PRs. If anything else pops up due to that PR, ping me and I will take a look.

> 
> @odanrc does this comment [#1785 (comment)](https://github.com/gem5/gem5/pull/1785#issuecomment-2533171895) still have accurate documentation on how to use the tags, or have these changes modified the API?

Nothing changed, but it would be useful to add the information that source files that use optional libraries should be declared under a respective guard check. Below I write more information to be appended to that message. Note that the Kconfig part is a deduction - I have never used/done that - so it may be incorrect.

+++++++++++++++++++++++++++++++++++++++

When an optional lib is used, a SConsopts file must be created/modified to populate the environment with the awareness of whether the compilation has or not the optional library. i.e.:

`env['CONF']['HAVE_LIB'] = True/False depending on whether the optional lib is present.`

Then, if the file that uses the optional lib to handles both having the lib or not, we make a respective macro visible in C++ by declaring it in a Kconfig file (if the directory does not contain this file yet, it can be created). i.e., something along the lines of the following must be added to that file:

```
config HAVE_LIB
    def_bool $(HAVE_LIB)
```

If, however, the file that uses the optional lib should not be compiled when the lib is not present, in the respective Sconscript file the Source() declaration that uses the optional library must be be declared only if that env flag is true.

For example, let's assume we are declaring a file that uses optional lib A:

```
// In SConsopts
import gem5_scons
with gem5_scons.Configure(main) as conf:
    conf.env['CONF']['HAVE_LIB_A'] = conf.CheckHeader('path_to_lib_a_header.h', '<>')

// In SConscript
if env['CONF']['HAVE_LIB_A']:
        Source('file_using_lib_a.cc', tags=['gem5 lib', 'lib a'])
```

**Comment by giactra** [comment]
I am not going to block this solution. Out of curiosity, what do you think about the following alternative?

```
// In SConsopts
import gem5_scons
with gem5_scons.Configure(main) as conf:
    conf.env['CONF']['HAVE_LIB_A'] = conf.CheckHeader('path_to_lib_a_header.h', '<>')

    if conf.env['CONF']['HAVE_LIB_A']:
        conf.env.TagImplies('lib a', 'gem5 lib')

// In SConscript
Source('file_using_lib_a.cc', tags=['lib a'])
```

As far as I can see this is what we are doing already for optional libs like FENV and PNG:

https://github.com/gem5/gem5/blob/stable/src/base/SConsopts#L47

It has the advantage of generating cleaner Sconscripts with the Sconsopts being responsible for source inclusion/exclusion.
Needless to say to make this work we should avoid having gem5 lib appended by default..

**Comment by odanrc** [comment]
> I am not going to block this solution. Out of curiosity, what do you think about the following alternative?
> 
> ```
> // In SConsopts
> import gem5_scons
> with gem5_scons.Configure(main) as conf:
>     conf.env['CONF']['HAVE_LIB_A'] = conf.CheckHeader('path_to_lib_a_header.h', '<>')
> 
>     if conf.env['CONF']['HAVE_LIB_A']:
>         conf.env.TagImplies('lib a', 'gem5 lib')
> 
> // In SConscript
> Source('file_using_lib_a.cc', tags=['lib a'])
> ```
> 
> As far as I can see this is what we are doing already for optional libs like FENV and PNG:
> 
> https://github.com/gem5/gem5/blob/stable/src/base/SConsopts#L47
> 
> It has the advantage of generating cleaner Sconscripts with the Sconsopts being responsible for source inclusion/exclusion. Needless to say to make this work we should avoid having gem5 lib appended by default..

This is exactly what I (quickly) tried in ´I tried the tag_gem5_lib=False approach to solve the protobuf situation, got stuck and backtracked to using the env checks. Then I realized what I mentioned in the 2 previous paragraphs, and made up my mind that it was indeed better to use env checks.´

As I said, that is (in theory) a valid solution, but:
- I think that the current solution is better, because it makes the intentions clearer. Someone learning gem5 can probably deduce what the if guard before a declaration of a Source does, while deducing that the reason the file they are modifying is not being compiled is because it does not have the gem5 lib tag is not exactly trivial
- I got errors when I tried it, and this version is working as it is. While I am normally keen to try alternative solutions in C++, I strongly dislike interpreted languages (a compiler would catch this: https://github.com/gem5/gem5/pull/1918), so I will only touch python if I need to fix stuff - I would rather leave any improvements to someone else

**Comment by giactra** [comment]
> > I am not going to block this solution. Out of curiosity, what do you think about the following alternative?
> > ```
> > // In SConsopts
> > import gem5_scons
> > with gem5_scons.Configure(main) as conf:
> >     conf.env['CONF']['HAVE_LIB_A'] = conf.CheckHeader('path_to_lib_a_header.h', '<>')
> > 
> >     if conf.env['CONF']['HAVE_LIB_A']:
> >         conf.env.TagImplies('lib a', 'gem5 lib')
> > 
> > // In SConscript
> > Source('file_using_lib_a.cc', tags=['lib a'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As far as I can see this is what we are doing already for optional libs like FENV and PNG:
> > https://github.com/gem5/gem5/blob/stable/src/base/SConsopts#L47
> > It has the advantage of generating cleaner Sconscripts with the Sconsopts being responsible for source inclusion/exclusion. Needless to say to make this work we should avoid having gem5 lib appended by default..
> 
> This is exactly what I (quickly) tried in ´I tried the tag_gem5_lib=False approach to solve the protobuf situation, got stuck and backtracked to using the env checks. Then I realized what I mentioned in the 2 previous paragraphs, and made up my mind that it was indeed better to use env checks.´
> 
> As I said, that is (in theory) a valid solution, but:
> 
>     * I think that the current solution is better, because it makes the intentions clearer. Someone learning gem5 can probably deduce what the if guard before a declaration of a Source does, while deducing that the reason the file they are modifying is not being compiled is because it does not have the gem5 lib tag is not exactly trivial

It also makes the use of tags somehow redundant or misleading... As having two different ways of doing exactly the same thing... Let alone the existing use of TagImplies which is still relying on the tagging mechanism to exclude/include sources..
Also in some cases it is explicit what is going on as you mentioned, like in:

```
if env['CONF']['LIB A']:
    Source(..)
```

It is less obvious in the many cases where this happens:

```
if not env['CONF']['LIB A']:
    return

[...]


Source(...)
Source(...)
```



> 
>     * I got errors when I tried it, and this version is working as it is. While I am normally keen to try alternative solutions in C++, I strongly dislike interpreted languages (a compiler would catch this: [scons: Fix missing and/or filter name #1918](https://github.com/gem5/gem5/pull/1918)), so I will only touch python if I need to fix stuff - I would rather leave any improvements to someone else

I understand we need to fix this to compile again gem5 (sigh).
So I am happy to merge this as it is provided you are open for me to try in the future to properly compile using tags

**Review by BobbyRBruce — APPROVED** [review]

**Comment by BobbyRBruce** [comment]
I'm going to merge this change just because I want this building error fixed. I welcome discussions about this and improvements to the build system generally, but I think this should be fixed first.

**Comment by odanrc** [comment]
> I understand we need to fix this to compile again gem5 (sigh). So I am happy to merge this as it is provided you are open for me to try in the future to properly compile using tags

Sure, feel free to ping me if I miss the PR when it comes.

**Comment by Harshil2107** [comment]
Hi @odanrc,

I’ve been investigating an issue causing a build failure in the SystemC daily test. This issue stems from changes introduced in PR #1785. While PR #1911 and PR #1918 addressed related problems, the build for the SystemC test still fails.  

### Context  

The SystemC daily test relies on building gem5 (libgem5_opt.so) with the following flags:  
`--with-cxx-config --without-python --without-tcmalloc --duplicate-sources`.  

After PR #1785 was merged, the following issues were observed:  

1. **Post-PR #1785:**  
   The build failed due to incomplete source filtering, resulting in:  
   ```
   TypeError: SourceFilter.__init__() missing 1 required positional argument: 'predicate':
     File "/__w/gem5/gem5/SConstruct", line 971:
       SConscript('src/SConscript', variant_dir=variant_path, exports=exports,
     File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 662:
       return method(*args, **kw)
     File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 598:
       return _SConscript(self.fs, *files, **subst_kw)
     File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 285:
       exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
     File "/__w/gem5/gem5/build/ARM/SConscript", line 723:
       lib_filter = lib_filter & without_tag('python')
     File "/__w/gem5/gem5/site_scons/gem5_scons/sources.py", line 143:
       return SourceFilter(
   ```  

2. **After PR #1911 and #1918:**  
   The error behavior changed, and the build includes Python-related sources, leading to:  
   ```
   build/ARM/sim/main.cc:29:10: fatal error: Python.h: No such file or directory
      29 | #include <Python.h>
         |          ^~~~~~~~~~
   compilation terminated.
   scons: *** [build/ARM/sim/main.os] Error 1
   scons: building terminated because of errors.
   ```  
   While these PRs fixed some bugs introduced by PR #1785, they did not resolve this issue for `--without-python` builds.  

### Steps to Reproduce  

You can reproduce the issue with the following commands (assuming your current working directory is the gem5 root):  
```bash  
docker pull ghcr.io/gem5/systemc-env:latest  
docker run -it --rm -u $UID:$GID -v ./:/workspace -w /workspace ghcr.io/gem5/systemc-env:latest  
scons build/ARM/gem5.opt --ignore-style --duplicate-sources -j$(nproc)  
scons setconfig build/ARM --ignore-style USE_SYSTEMC=n  
scons build/ARM/libgem5_opt.so --with-cxx-config --without-python --without-tcmalloc -j$(nproc) --duplicate-sources  
```  

Would it be possible for you to take a look at this error? I’m happy to provide more context and details if needed.  

Thank you.

**Comment by odanrc** [comment]
> Hi @odanrc,
> 
> I’ve been investigating an issue causing a build failure in the SystemC daily test. This issue stems from changes introduced in PR #1785. While PR #1911 and PR #1918 addressed related problems, the build for the SystemC test still fails.
> ### Context
> 
> The SystemC daily test relies on building gem5 (libgem5_opt.so) with the following flags: `--with-cxx-config --without-python --without-tcmalloc --duplicate-sources`.
> 
> After PR #1785 was merged, the following issues were observed:
> 
>     1. **Post-PR [misc: Fix scons tags #1785](https://github.com/gem5/gem5/pull/1785):**
>        The build failed due to incomplete source filtering, resulting in:
>        ```
>        TypeError: SourceFilter.__init__() missing 1 required positional argument: 'predicate':
>          File "/__w/gem5/gem5/SConstruct", line 971:
>            SConscript('src/SConscript', variant_dir=variant_path, exports=exports,
>          File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 662:
>            return method(*args, **kw)
>          File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 598:
>            return _SConscript(self.fs, *files, **subst_kw)
>          File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 285:
>            exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
>          File "/__w/gem5/gem5/build/ARM/SConscript", line 723:
>            lib_filter = lib_filter & without_tag('python')
>          File "/__w/gem5/gem5/site_scons/gem5_scons/sources.py", line 143:
>            return SourceFilter(
>        ```
> 
>     2. **After PR [misc: Fixup optional libs being required #1911](https://github.com/gem5/gem5/pull/1911) and [scons: Fix missing and/or filter name #1918](https://github.com/gem5/gem5/pull/1918):**
>        The error behavior changed, and the build includes Python-related sources, leading to:
>        ```
>        build/ARM/sim/main.cc:29:10: fatal error: Python.h: No such file or directory
>           29 | #include <Python.h>
>              |          ^~~~~~~~~~
>        compilation terminated.
>        scons: *** [build/ARM/sim/main.os] Error 1
>        scons: building terminated because of errors.
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        While these PRs fixed some bugs introduced by PR [misc: Fix scons tags #1785](https://github.com/gem5/gem5/pull/1785), they did not resolve this issue for `--without-python` builds.
> 
> 
> ### Steps to Reproduce
> 
> You can reproduce the issue with the following commands (assuming your current working directory is the gem5 root):
> 
> ```shell
> docker pull ghcr.io/gem5/systemc-env:latest  
> docker run -it --rm -u $UID:$GID -v ./:/workspace -w /workspace ghcr.io/gem5/systemc-env:latest  
> scons build/ARM/gem5.opt --ignore-style --duplicate-sources -j$(nproc)  
> scons setconfig build/ARM --ignore-style USE_SYSTEMC=n  
> scons build/ARM/libgem5_opt.so --with-cxx-config --without-python --without-tcmalloc -j$(nproc) --duplicate-sources  
> ```
> 
> Would it be possible for you to take a look at this error? I’m happy to provide more context and details if needed.
> 
> Thank you.

I will take a look at it. Thanks for the detailed report!
