### ISSUE TITLE
gem5 pre-commit hooks installation failed

### ISSUE THREAD

**Issue by hnpl** [gem5/gem5#633]
**Describe the bug**
gem5 pre-commit hooks installation failed.

**Affects version**
Current develop (https://github.com/gem5/gem5/commit/bfd25f535216dbc3cca6a5fb9bc70da18f4068b3). I suspect the bug was introduced by #431.

**gem5 Modifications**
N/A

**To Reproduce**

```sh
scons build/RISCV/gem5.opt -j 10
```

**Terminal Output**

```shell
scons: Reading SConscript files ...

You're missing the pre-commit/commit-msg hooks. These hook help to ensure your
code follows gem5's style rules on git commit and your commit messages follow
our commit message requirements. This script will now install these hooks in
your .git/hooks/ directory.
Press enter to continue, or ctrl-c to abort:
 AttributeError: module 'asyncio.subprocess' has no attribute 'call':
  File "/scr/hn/DEV-gem5/riscv-bootloader-stdlib/SConstruct", line 183:
    main = Environment(tools=[
  File "/home/hn/.local/lib/python3.10/site-packages/SCons/Environment.py", line 1030:
    apply_tools(self, tools, toolpath)
  File "/home/hn/.local/lib/python3.10/site-packages/SCons/Environment.py", line 116:
    _ = env.Tool(tool)
  File "/home/hn/.local/lib/python3.10/site-packages/SCons/Environment.py", line 1906:
    tool(self)
  File "/home/hn/.local/lib/python3.10/site-packages/SCons/Tool/__init__.py", line 265:
    self.generate(env, *args, **kw)
  File "/scr/hn/DEV-gem5/riscv-bootloader-stdlib/site_scons/site_tools/git.py", line 112:
    install_style_hooks(env)
  File "/scr/hn/DEV-gem5/riscv-bootloader-stdlib/site_scons/site_tools/git.py", line 90:
    ret = subprocess.call(str(pre_commit_install), shell=True)
```

**Host Operating System**
Ubuntu 22.04 / Python 3.10

**Host ISA**
ARM

**Compiler used**
gcc-11

**Additional information**
I believe this is a bug that was surfaced by #431.

https://github.com/gem5/gem5/commit/d11c40dcac927b9501b61fed66b7144de648a4d8#diff-5a01b9b25a06c26dbc839ddf91d234ea0ef0534b5b5813acb6d8b64317a3a0fdL41

`subprocess` has the `call()` function, `asyncio.subprocess` does not.
